### ISSUE TITLE
[RFE] sg-core should be able to listen on more than one amqp address

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/sg-core#12]
This is a feature request.

sg-core should be able to listen on more than one amqp address at a time. It should also label the incoming metrics with the address, and any other metadata that would make it more clear which cloud the metrics are associated with.

**Comment by paramite** [comment]
I believe that with the recent refactor this is true.

**Comment by leifmadsen** [comment]
> I believe that with the recent refactor this is true.

I would think so yea. Is there a quick test that can get run at some point to verify this? Once verified feel free to close this out! Thanks!

**Comment by vyzigold** [comment]
So, I've been thinking about this and decided to try it.

I used 2 different applications writing logs to 2 different amqp addresses. For each address I run a separate sg-bridge, each listening on one of the amqp addresses and sending logs to a different socket:
```
./bridge --amqp_url=amqp://127.0.0.1:5672/collectd --gw_unix=/tmp/smartgateway
```
```
./bridge --amqp_url=amqp://127.0.0.1:5672/logs --gw_unix=/tmp/logs
```

Then I configured sg-core to listen on both of the sockets at once (I used 2 socket transport plugins and 2 logs handlers) and after a quick small patch (each transport plugin requires a unique name) to sg-core I was successfully able to get logs from both amqp addresses to Loki. The required patch (along with my config) can be seen [here](https://github.com/vyzigold/sg-core/commit/a69c365fbac6a3b2f711c804754f86a6238e4e6e) (It will require a few more things if we want to use it).

The config I used:
```
pluginDir: /tmp/plugins
logLevel: debug
transports:
    - name: socket
      config:
          path: "/tmp/smartgateway"
      handlers:
      - name: logs
        config:
            timestampField: "@timestamp"
            messageField: "message"
            severityField: "severity"
            hostnameField: "host"
    - name: socket
      config:
          path: "/tmp/logs"
      handlers:
      - name: logs
        config:
            timestampField: "@timestamp"
            messageField: "message"
            severityField: "severity"
            hostnameField: "host"
applications: 
  - name: loki
    config:
        connection: "http://localhost:3100"
        maxwaittime: 5s
```
Do we want this functionality?
